export const COUNTRIES = [
  "India",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Singapore",
  "Australia",
  "Canada",
  "Germany",
  "France",
  "Japan",
  "Malaysia",
  "Thailand",
  "Sri Lanka",
  "Nepal",
  "Bangladesh",
  "Maldives",
  "Saudi Arabia",
  "Qatar",
  "Kuwait",
  "Bahrain",
  "Oman",
  "New Zealand",
  "South Africa",
  "Italy",
  "Spain",
  "Netherlands",
];
